"""
Plot desired circles, FK workspace (sampled), and circle points projected onto the workspace.

Uses an FK workspace cache (e.g. a dense grid) and projects each desired point to a nearby
workspace point with a continuity preference to avoid branch-jumps.

Default workspace (generated by `scripts/fk_workspace_grid.py`):
  - data/output/workspace_fk_ins94.3_b0.3_step0.01_int0.2.npz
"""

from __future__ import annotations

import argparse
import os
from pathlib import Path
from typing import Tuple

import numpy as np

os.environ.setdefault("MPLCONFIGDIR", "/tmp/mpl")
import matplotlib.pyplot as plt  # noqa: E402

from scipy.spatial import cKDTree  # noqa: E402

def circle_points(center_xyz: np.ndarray, radius: float, n: int, start_angle: float) -> np.ndarray:
    angles = start_angle + np.linspace(0.0, 2.0 * np.pi, int(n), endpoint=False, dtype=np.float64)
    pts = np.repeat(center_xyz.reshape(1, 3), int(n), axis=0)
    pts[:, 0] = center_xyz[0] + radius * np.cos(angles)
    pts[:, 1] = center_xyz[1] + radius * np.sin(angles)
    return pts


def choose_z0_from_workspace(P_ok: np.ndarray, center_xy: Tuple[float, float]) -> float:
    cx, cy = float(center_xy[0]), float(center_xy[1])
    # Prefer points close to the circle center in XY; widen progressively if empty.
    for r in (5.0, 10.0, 20.0, 40.0):
        m = (np.abs(P_ok[:, 0] - cx) <= r) & (np.abs(P_ok[:, 1] - cy) <= r)
        if np.any(m):
            return float(np.median(P_ok[m, 2]))
    return float(np.median(P_ok[:, 2]))


def project_to_workspace_continuous(
    p_des: np.ndarray,
    P_ok: np.ndarray,
    *,
    k_nearest: int = 200,
    continuity_weight: float = 0.25,
) -> np.ndarray:
    k = int(max(1, min(k_nearest, len(P_ok))))
    p_proj = np.zeros_like(p_des)

    prev_p = None
    for i in range(len(p_des)):
        d_des = np.linalg.norm(P_ok - p_des[i], axis=1)
        if prev_p is None:
            j = int(np.argmin(d_des))
        else:
            cand = np.argpartition(d_des, k - 1)[:k]
            d_prev = np.linalg.norm(P_ok[cand] - prev_p, axis=1)
            score = d_des[cand] + float(continuity_weight) * d_prev
            j = int(cand[int(np.argmin(score))])
        p_proj[i] = P_ok[j]
        prev_p = p_proj[i]

    return p_proj


def project_to_workspace_dp(
    p_des: np.ndarray,
    P_ok: np.ndarray,
    U_ok: np.ndarray,
    tree: "cKDTree",
    *,
    k_nearest: int = 200,
    alpha_u: float = 0.25,
) -> np.ndarray:
    """
    Discrete projection onto a sampled workspace using a globally-smoothed path:

      minimize sum_i ||P(ws_i) - p_des_i|| + alpha_u * ||U(ws_i) - U(ws_{i-1})||

    Uses DP/Viterbi over K nearest candidates per point.
    """
    n = int(p_des.shape[0])
    k = int(max(1, k_nearest))

    dists, idxs = tree.query(p_des, k=k, workers=-1)
    if k == 1:
        dists = dists.reshape(n, 1)
        idxs = idxs.reshape(n, 1)

    dp = np.full((n, k), np.inf, dtype=np.float64)
    bp = np.full((n, k), -1, dtype=np.int32)
    dp[0] = dists[0]

    for i in range(1, n):
        prev_u = U_ok[idxs[i - 1]]  # (k,3)
        cur_u = U_ok[idxs[i]]  # (k,3)
        trans = alpha_u * np.linalg.norm(prev_u[:, None, :] - cur_u[None, :, :], axis=2)  # (k,k)
        total = dp[i - 1][:, None] + trans  # (k,k)
        argmin = np.argmin(total, axis=0)  # (k,)
        dp[i] = dists[i] + total[argmin, np.arange(k)]
        bp[i] = argmin.astype(np.int32)

    j = int(np.argmin(dp[-1]))
    sel = np.zeros((n,), dtype=np.int32)
    for i in range(n - 1, -1, -1):
        sel[i] = idxs[i, j]
        j = int(bp[i, j]) if i > 0 else j

    return P_ok[sel]


def plot_xy(
    P_ok: np.ndarray,
    p_des_1: np.ndarray,
    p_des_2: np.ndarray,
    p_proj_1: np.ndarray,
    p_proj_2: np.ndarray,
    out_png: Path,
    *,
    max_ws_points: int = 250_000,
) -> None:
    P_plot = P_ok
    if P_plot.shape[0] > max_ws_points:
        idx = np.linspace(0, P_plot.shape[0] - 1, max_ws_points, dtype=int)
        P_plot = P_plot[idx]

    fig, ax = plt.subplots(1, 1, figsize=(9, 9))
    ax.scatter(P_plot[:, 0], P_plot[:, 1], s=2, alpha=0.18, label="FK workspace")
    ax.plot(p_des_1[:, 0], p_des_1[:, 1], lw=2.0, label="desired (+y)")
    ax.plot(p_des_2[:, 0], p_des_2[:, 1], lw=2.0, label="desired (-y)")
    ax.scatter(p_proj_1[:, 0], p_proj_1[:, 1], s=10, label="projected (+y)")
    ax.scatter(p_proj_2[:, 0], p_proj_2[:, 1], s=10, label="projected (-y)")
    ax.set_title("Desired circles and projection onto FK workspace (XY)")
    ax.set_xlabel("x (mm)")
    ax.set_ylabel("y (mm)")
    ax.axis("equal")
    ax.grid(True, alpha=0.25)
    ax.legend(loc="best")
    fig.tight_layout()
    fig.savefig(out_png, dpi=200)
    plt.close(fig)


def plot_multiview(
    P_ok: np.ndarray,
    p_des_1: np.ndarray,
    p_des_2: np.ndarray,
    p_proj_1: np.ndarray,
    p_proj_2: np.ndarray,
    out_png: Path,
    *,
    max_ws_points: int = 250_000,
) -> None:
    P_plot = P_ok
    if P_plot.shape[0] > max_ws_points:
        idx = np.linspace(0, P_plot.shape[0] - 1, max_ws_points, dtype=int)
        P_plot = P_plot[idx]

    colors = {
        "ws": "0.6",
        "des1": "tab:blue",
        "des2": "tab:orange",
        "proj1": "tab:green",
        "proj2": "tab:red",
    }

    fig = plt.figure(figsize=(12, 9))

    ax = fig.add_subplot(2, 2, 1, projection="3d")
    ax.scatter(P_plot[:, 0], P_plot[:, 1], P_plot[:, 2], s=2, alpha=0.08, c=colors["ws"], label="workspace")
    ax.plot(p_des_1[:, 0], p_des_1[:, 1], p_des_1[:, 2], lw=2.0, c=colors["des1"], label="desired (+y)")
    ax.plot(p_des_2[:, 0], p_des_2[:, 1], p_des_2[:, 2], lw=2.0, c=colors["des2"], label="desired (-y)")
    ax.scatter(p_proj_1[:, 0], p_proj_1[:, 1], p_proj_1[:, 2], s=10, c=colors["proj1"], label="projected (+y)")
    ax.scatter(p_proj_2[:, 0], p_proj_2[:, 1], p_proj_2[:, 2], s=10, c=colors["proj2"], label="projected (-y)")
    ax.set_title("3D")
    ax.set_xlabel("x (mm)")
    ax.set_ylabel("y (mm)")
    ax.set_zlabel("z (mm)")
    ax.legend(loc="best")

    ax = fig.add_subplot(2, 2, 2)
    ax.scatter(P_plot[:, 0], P_plot[:, 1], s=2, alpha=0.18, c=colors["ws"], label="workspace")
    ax.plot(p_des_1[:, 0], p_des_1[:, 1], lw=2.0, c=colors["des1"], label="desired (+y)")
    ax.plot(p_des_2[:, 0], p_des_2[:, 1], lw=2.0, c=colors["des2"], label="desired (-y)")
    ax.scatter(p_proj_1[:, 0], p_proj_1[:, 1], s=10, c=colors["proj1"], label="projected (+y)")
    ax.scatter(p_proj_2[:, 0], p_proj_2[:, 1], s=10, c=colors["proj2"], label="projected (-y)")
    ax.set_title("XY")
    ax.set_xlabel("x (mm)")
    ax.set_ylabel("y (mm)")
    ax.axis("equal")
    ax.grid(True, alpha=0.25)
    ax.legend(loc="best")

    ax = fig.add_subplot(2, 2, 3)
    ax.scatter(P_plot[:, 0], P_plot[:, 2], s=2, alpha=0.18, c=colors["ws"], label="workspace")
    ax.plot(p_des_1[:, 0], p_des_1[:, 2], lw=2.0, c=colors["des1"], label="desired (+y)")
    ax.plot(p_des_2[:, 0], p_des_2[:, 2], lw=2.0, c=colors["des2"], label="desired (-y)")
    ax.scatter(p_proj_1[:, 0], p_proj_1[:, 2], s=10, c=colors["proj1"], label="projected (+y)")
    ax.scatter(p_proj_2[:, 0], p_proj_2[:, 2], s=10, c=colors["proj2"], label="projected (-y)")
    ax.set_title("XZ")
    ax.set_xlabel("x (mm)")
    ax.set_ylabel("z (mm)")
    ax.grid(True, alpha=0.25)
    ax.legend(loc="best")

    ax = fig.add_subplot(2, 2, 4)
    ax.scatter(P_plot[:, 1], P_plot[:, 2], s=2, alpha=0.18, c=colors["ws"], label="workspace")
    ax.plot(p_des_1[:, 1], p_des_1[:, 2], lw=2.0, c=colors["des1"], label="desired (+y)")
    ax.plot(p_des_2[:, 1], p_des_2[:, 2], lw=2.0, c=colors["des2"], label="desired (-y)")
    ax.scatter(p_proj_1[:, 1], p_proj_1[:, 2], s=10, c=colors["proj1"], label="projected (+y)")
    ax.scatter(p_proj_2[:, 1], p_proj_2[:, 2], s=10, c=colors["proj2"], label="projected (-y)")
    ax.set_title("YZ")
    ax.set_xlabel("y (mm)")
    ax.set_ylabel("z (mm)")
    ax.grid(True, alpha=0.25)
    ax.legend(loc="best")

    fig.tight_layout()
    fig.savefig(out_png, dpi=200)
    plt.close(fig)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--workspace", default="data/output/workspace_fk_ins94.3_b0.3_step0.01_int0.2.npz")
    ap.add_argument("--center-y", type=float, default=40.0, help="Circle centers at y=±center-y, x=0")
    ap.add_argument("--radius", type=float, default=10.0)
    ap.add_argument("--points", type=int, default=100)
    ap.add_argument("--start-angle", type=float, default=-np.pi / 2.0)
    ap.add_argument("--k-nearest", type=int, default=200)
    ap.add_argument("--method", choices=["greedy", "dp"], default="dp")
    ap.add_argument("--continuity-weight", type=float, default=0.25, help="Greedy only: weight on ||p - prev_p||")
    ap.add_argument("--alpha-u", type=float, default=0.25, help="DP only: weight on ||u_i - u_{i-1}||")
    args = ap.parse_args()

    ws_path = Path(args.workspace)
    data = np.load(ws_path)
    P = np.asarray(data["P"], dtype=np.float64)
    U = np.asarray(data["U"], dtype=np.float64) if "U" in data else None
    conv = np.asarray(data["conv"]).astype(bool)
    ok = conv & np.isfinite(P).all(axis=1)
    P_ok = P[ok]
    if U is None:
        raise RuntimeError("Workspace NPZ is missing 'U' currents; regenerate with scripts/fk_workspace_grid.py")
    U_ok = U[ok]
    if P_ok.size == 0:
        raise RuntimeError(f"No converged workspace points found in {ws_path}")

    tree = cKDTree(P_ok)

    c1_xy = (0.0, float(args.center_y))
    c2_xy = (0.0, -float(args.center_y))
    z0_1 = choose_z0_from_workspace(P_ok, c1_xy)
    z0_2 = choose_z0_from_workspace(P_ok, c2_xy)

    p_des_1 = circle_points(np.array([c1_xy[0], c1_xy[1], z0_1], dtype=np.float64), float(args.radius), int(args.points), float(args.start_angle))
    p_des_2 = circle_points(np.array([c2_xy[0], c2_xy[1], z0_2], dtype=np.float64), float(args.radius), int(args.points), float(args.start_angle))

    if args.method == "dp":
        p_proj_1 = project_to_workspace_dp(
            p_des_1,
            P_ok,
            U_ok,
            tree,
            k_nearest=int(args.k_nearest),
            alpha_u=float(args.alpha_u),
        )
        p_proj_2 = project_to_workspace_dp(
            p_des_2,
            P_ok,
            U_ok,
            tree,
            k_nearest=int(args.k_nearest),
            alpha_u=float(args.alpha_u),
        )
    else:
        p_proj_1 = project_to_workspace_continuous(
            p_des_1,
            P_ok,
            k_nearest=int(args.k_nearest),
            continuity_weight=float(args.continuity_weight),
        )
        p_proj_2 = project_to_workspace_continuous(
            p_des_2,
            P_ok,
            k_nearest=int(args.k_nearest),
            continuity_weight=float(args.continuity_weight),
        )

    plots_dir = Path("plots")
    plots_dir.mkdir(parents=True, exist_ok=True)
    out_png = plots_dir / f"circle_workspace_projection_xy_y{int(abs(args.center_y))}_r{int(args.radius)}.png"
    plot_xy(P_ok, p_des_1, p_des_2, p_proj_1, p_proj_2, out_png)

    out_mv = plots_dir / f"circle_workspace_projection_multiview_y{int(abs(args.center_y))}_r{int(args.radius)}.png"
    plot_multiview(P_ok, p_des_1, p_des_2, p_proj_1, p_proj_2, out_mv)

    d1 = np.linalg.norm(p_des_1 - p_proj_1, axis=1)
    d2 = np.linalg.norm(p_des_2 - p_proj_2, axis=1)
    print(f"Workspace points (converged): {P_ok.shape[0]}")
    print(f"Projection method: {args.method}")
    print(f"Projection error (+y): mean={d1.mean():.3f}mm p95={np.percentile(d1,95):.3f}mm max={d1.max():.3f}mm")
    print(f"Projection error (-y): mean={d2.mean():.3f}mm p95={np.percentile(d2,95):.3f}mm max={d2.max():.3f}mm")
    print(f"Saved: {out_png}")
    print(f"Saved: {out_mv}")


if __name__ == "__main__":
    main()
