"""
FK/IK consistency test using a dense FK workspace cache + DP-smoothed projection.

Workflow:
  1) Load dense workspace (U,P,conv) from an NPZ (generated by scripts/fk_workspace_grid.py).
  2) Build desired circles in tip space (fixed-z plane chosen from workspace near the circle center).
  3) Project each circle point onto workspace using DP/Viterbi over K nearest candidates, penalizing
     current jumps: sum ||p_ws - p_des|| + alpha_u * ||u_ws(i) - u_ws(i-1)||.
  4) Run MATLAB-style normalized pseudoinverse IK to track the projected targets (reachable by construction).
  5) Report FK/IK errors and save multiview plots.

Run:
  MPLCONFIGDIR=/tmp/mpl python3 scripts/fk_ik_test_projected_workspace_dp.py
"""

from __future__ import annotations

import os
from dataclasses import dataclass
from pathlib import Path
from typing import Tuple

import numpy as np

os.environ.setdefault("MPLCONFIGDIR", "/tmp/mpl")
import matplotlib.pyplot as plt  # noqa: E402

from scipy.spatial import cKDTree  # noqa: E402

from crm_ml_rl.wrappers import crm_python  # noqa: E402


@dataclass(frozen=True)
class Config:
    # Workspace cache (dense)
    workspace_npz: str = "output_data/workspace_fk_ins94.3_b0.3_step0.01_int0.2.npz"

    # FK/IK settings
    insertion_length: float = 94.3
    integration_step_size: float = 0.2  # match MEX default
    param_file: str = "catheterdata/CatheterParameterSet_1_dyn.txt"
    config_file: str = "catheterdata/CatheterSpatialConfiguration_1.txt"

    # Desired circles
    radius_mm: float = 10.0
    center1_xy: Tuple[float, float] = (0.0, 40.0)
    center2_xy: Tuple[float, float] = (0.0, -40.0)
    points_per_circle: int = 200
    start_angle_rad: float = -np.pi / 2.0

    # DP projection params
    k_nearest: int = 300
    alpha_u: float = 0.4

    # MATLAB-style normalized pinv IK params
    # For tighter FK/IK matching, reduce step and tighten thresholds.
    step_size: float = 1e-3
    threshold_start_mm: float = 0.1
    threshold_traj_mm: float = 0.1
    itrmax: int = 500

    # Export
    export_csv: bool = True


def circle_points(center_xyz: np.ndarray, radius: float, n: int, start_angle: float) -> np.ndarray:
    angles = start_angle + np.linspace(0.0, 2.0 * np.pi, int(n), endpoint=False, dtype=np.float64)
    pts = np.repeat(center_xyz.reshape(1, 3), int(n), axis=0)
    pts[:, 0] = center_xyz[0] + radius * np.cos(angles)
    pts[:, 1] = center_xyz[1] + radius * np.sin(angles)
    return pts


def choose_z0_from_workspace(P_ok: np.ndarray, center_xy: Tuple[float, float]) -> float:
    cx, cy = float(center_xy[0]), float(center_xy[1])
    for r in (5.0, 10.0, 20.0, 40.0):
        m = (np.abs(P_ok[:, 0] - cx) <= r) & (np.abs(P_ok[:, 1] - cy) <= r)
        if np.any(m):
            return float(np.median(P_ok[m, 2]))
    return float(np.median(P_ok[:, 2]))


def project_dp_indices(
    p_des: np.ndarray,
    P_ok: np.ndarray,
    U_ok: np.ndarray,
    tree: "cKDTree",
    *,
    k_nearest: int,
    alpha_u: float,
) -> np.ndarray:
    n = int(p_des.shape[0])
    k = int(max(1, k_nearest))
    dists, idxs = tree.query(p_des, k=k, workers=-1)
    if k == 1:
        dists = dists.reshape(n, 1)
        idxs = idxs.reshape(n, 1)

    dp = np.full((n, k), np.inf, dtype=np.float64)
    bp = np.full((n, k), -1, dtype=np.int32)
    dp[0] = dists[0]

    for i in range(1, n):
        prev_u = U_ok[idxs[i - 1]]
        cur_u = U_ok[idxs[i]]
        trans = float(alpha_u) * np.linalg.norm(prev_u[:, None, :] - cur_u[None, :, :], axis=2)
        total = dp[i - 1][:, None] + trans
        argmin = np.argmin(total, axis=0)
        dp[i] = dists[i] + total[argmin, np.arange(k)]
        bp[i] = argmin.astype(np.int32)

    j = int(np.argmin(dp[-1]))
    sel = np.zeros((n,), dtype=np.int32)
    for i in range(n - 1, -1, -1):
        sel[i] = idxs[i, j]
        j = int(bp[i, j]) if i > 0 else j
    return sel


def pinv_normalized_track(
    cfg: Config,
    kin: "crm_python.CRMKinematics",
    p_targets: np.ndarray,
    u_start: np.ndarray,
    threshold_mm: float,
    du0_guess: np.ndarray | None,
) -> Tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray | None]:
    U_out = np.zeros((len(p_targets), 3), dtype=np.float64)
    P_fk = np.zeros((len(p_targets), 3), dtype=np.float64)
    err = np.zeros((len(p_targets),), dtype=np.float64)

    u = np.asarray(u_start, dtype=np.float64).reshape(3).copy()
    for i in range(len(p_targets)):
        thr = cfg.threshold_start_mm if i == 0 else threshold_mm
        for _ in range(int(cfg.itrmax)):
            if du0_guess is None:
                out = kin.fk_and_jacobian(u, cfg.insertion_length)
            else:
                out = kin.fk_and_jacobian(u, cfg.insertion_length, du0_guess)
            p = np.asarray(out["tip_position"], dtype=np.float64).reshape(3)
            du0_guess = np.asarray(out["delta_u0"], dtype=np.float64).reshape(3)
            J = np.asarray(out["jacobian"], dtype=np.float64)[:3, :3]
            e = p_targets[i] - p
            e_norm = float(np.linalg.norm(e))
            if e_norm <= thr:
                break
            du = np.linalg.pinv(J) @ e
            du_norm = float(np.linalg.norm(du))
            if du_norm < 1e-12 or not np.isfinite(du_norm):
                break
            u = u + cfg.step_size * (du / du_norm)

        if du0_guess is None:
            out = kin.forward_kinematics(u, cfg.insertion_length)
        else:
            out = kin.forward_kinematics_with_guess(u, cfg.insertion_length, du0_guess)
        p = np.asarray(out["tip_position"], dtype=np.float64).reshape(3)
        du0_guess = np.asarray(out["delta_u0"], dtype=np.float64).reshape(3)

        U_out[i] = u
        P_fk[i] = p
        err[i] = float(np.linalg.norm(p_targets[i] - p))

    return U_out, P_fk, err, du0_guess


def plot_multiview(
    P_ok: np.ndarray,
    p_des: np.ndarray,
    p_proj: np.ndarray,
    p_fk: np.ndarray,
    out_png: Path,
    *,
    max_ws_points: int = 250_000,
) -> None:
    P_plot = P_ok
    if P_plot.shape[0] > max_ws_points:
        idx = np.linspace(0, P_plot.shape[0] - 1, max_ws_points, dtype=int)
        P_plot = P_plot[idx]

    colors = {"ws": "0.6", "des": "tab:blue", "proj": "tab:orange", "fk": "tab:green"}

    fig = plt.figure(figsize=(12, 9))
    ax = fig.add_subplot(2, 2, 1, projection="3d")
    ax.scatter(P_plot[:, 0], P_plot[:, 1], P_plot[:, 2], s=2, alpha=0.06, c=colors["ws"], label="workspace")
    ax.plot(p_des[:, 0], p_des[:, 1], p_des[:, 2], lw=2.0, c=colors["des"], label="desired")
    ax.scatter(p_proj[:, 0], p_proj[:, 1], p_proj[:, 2], s=12, c=colors["proj"], label="projected(ws)")
    ax.plot(p_fk[:, 0], p_fk[:, 1], p_fk[:, 2], lw=2.0, c=colors["fk"], label="FK( IK currents )")
    ax.set_title("3D")
    ax.legend(loc="best")

    ax = fig.add_subplot(2, 2, 2)
    ax.scatter(P_plot[:, 0], P_plot[:, 1], s=2, alpha=0.12, c=colors["ws"], label="workspace")
    ax.plot(p_des[:, 0], p_des[:, 1], lw=2.0, c=colors["des"], label="desired")
    ax.scatter(p_proj[:, 0], p_proj[:, 1], s=12, c=colors["proj"], label="projected(ws)")
    ax.plot(p_fk[:, 0], p_fk[:, 1], lw=2.0, c=colors["fk"], label="FK")
    ax.set_title("XY")
    ax.axis("equal")
    ax.grid(True, alpha=0.25)
    ax.legend(loc="best")

    ax = fig.add_subplot(2, 2, 3)
    ax.scatter(P_plot[:, 0], P_plot[:, 2], s=2, alpha=0.12, c=colors["ws"], label="workspace")
    ax.plot(p_des[:, 0], p_des[:, 2], lw=2.0, c=colors["des"], label="desired")
    ax.scatter(p_proj[:, 0], p_proj[:, 2], s=12, c=colors["proj"], label="projected(ws)")
    ax.plot(p_fk[:, 0], p_fk[:, 2], lw=2.0, c=colors["fk"], label="FK")
    ax.set_title("XZ")
    ax.grid(True, alpha=0.25)
    ax.legend(loc="best")

    ax = fig.add_subplot(2, 2, 4)
    ax.scatter(P_plot[:, 1], P_plot[:, 2], s=2, alpha=0.12, c=colors["ws"], label="workspace")
    ax.plot(p_des[:, 1], p_des[:, 2], lw=2.0, c=colors["des"], label="desired")
    ax.scatter(p_proj[:, 1], p_proj[:, 2], s=12, c=colors["proj"], label="projected(ws)")
    ax.plot(p_fk[:, 1], p_fk[:, 2], lw=2.0, c=colors["fk"], label="FK")
    ax.set_title("YZ")
    ax.grid(True, alpha=0.25)
    ax.legend(loc="best")

    fig.tight_layout()
    fig.savefig(out_png, dpi=200)
    plt.close(fig)


def summarize_err(label: str, e: np.ndarray, thr: float) -> None:
    pct = float(np.mean(e <= thr)) * 100.0
    print(f"{label}: mean={e.mean():.3f}mm p95={np.percentile(e,95):.3f}mm max={e.max():.3f}mm <= {thr:.1f}mm={pct:.1f}%")


def main() -> None:
    cfg = Config()

    ws = np.load(cfg.workspace_npz)
    P = np.asarray(ws["P"], dtype=np.float64)
    U = np.asarray(ws["U"], dtype=np.float64)
    conv = np.asarray(ws["conv"]).astype(bool)
    ok = conv & np.isfinite(P).all(axis=1)
    P_ok = P[ok]
    U_ok = U[ok]
    if P_ok.size == 0:
        raise RuntimeError(f"No converged points in {cfg.workspace_npz}")

    tree = cKDTree(P_ok)

    z1 = choose_z0_from_workspace(P_ok, cfg.center1_xy)
    z2 = choose_z0_from_workspace(P_ok, cfg.center2_xy)
    p_des_1 = circle_points(np.array([cfg.center1_xy[0], cfg.center1_xy[1], z1], dtype=np.float64), cfg.radius_mm, cfg.points_per_circle, cfg.start_angle_rad)
    p_des_2 = circle_points(np.array([cfg.center2_xy[0], cfg.center2_xy[1], z2], dtype=np.float64), cfg.radius_mm, cfg.points_per_circle, cfg.start_angle_rad)

    sel1 = project_dp_indices(p_des_1, P_ok, U_ok, tree, k_nearest=cfg.k_nearest, alpha_u=cfg.alpha_u)
    sel2 = project_dp_indices(p_des_2, P_ok, U_ok, tree, k_nearest=cfg.k_nearest, alpha_u=cfg.alpha_u)
    p_proj_1 = P_ok[sel1]
    p_proj_2 = P_ok[sel2]
    u_seed_1 = U_ok[sel1]
    u_seed_2 = U_ok[sel2]

    # IK tracking (MATLAB-style pinv, normalized step)
    kin = crm_python.CRMKinematics()
    if not kin.load_parameters(cfg.param_file, cfg.config_file):
        raise RuntimeError("Failed to load parameters for kinematics.")
    kin.integration_step_size = float(cfg.integration_step_size)

    du0_guess = None
    U1, P1_fk, e1, du0_guess = pinv_normalized_track(cfg, kin, p_proj_1, u_seed_1[0], cfg.threshold_traj_mm, du0_guess)
    U2, P2_fk, e2, du0_guess = pinv_normalized_track(cfg, kin, p_proj_2, u_seed_2[0], cfg.threshold_traj_mm, du0_guess)

    # Errors
    e1_proj = np.linalg.norm(p_des_1 - p_proj_1, axis=1)
    e2_proj = np.linalg.norm(p_des_2 - p_proj_2, axis=1)
    e1_des_fk = np.linalg.norm(p_des_1 - P1_fk, axis=1)
    e2_des_fk = np.linalg.norm(p_des_2 - P2_fk, axis=1)

    print(f"Workspace (converged): {P_ok.shape[0]}")
    print(f"DP projection: k={cfg.k_nearest} alpha_u={cfg.alpha_u}")
    summarize_err("Circle1 projection ||des-proj||", e1_proj, thr=cfg.threshold_traj_mm)
    summarize_err("Circle2 projection ||des-proj||", e2_proj, thr=cfg.threshold_traj_mm)
    summarize_err("Circle1 FK/IK ||proj-fk||", e1, thr=cfg.threshold_traj_mm)
    summarize_err("Circle2 FK/IK ||proj-fk||", e2, thr=cfg.threshold_traj_mm)
    summarize_err("Circle1 desired tracking ||des-fk||", e1_des_fk, thr=cfg.threshold_traj_mm)
    summarize_err("Circle2 desired tracking ||des-fk||", e2_des_fk, thr=cfg.threshold_traj_mm)

    out_dir = Path("output_data")
    out_dir.mkdir(parents=True, exist_ok=True)
    out_npz = out_dir / "fk_ik_test_dp_projection.npz"
    np.savez_compressed(
        out_npz,
        circle1_des=p_des_1,
        circle2_des=p_des_2,
        circle1_proj=p_proj_1,
        circle2_proj=p_proj_2,
        circle1_fk=P1_fk,
        circle2_fk=P2_fk,
        circle1_currents=U1,
        circle2_currents=U2,
        circle1_err_proj_fk=e1,
        circle2_err_proj_fk=e2,
        circle1_err_des_proj=e1_proj,
        circle2_err_des_proj=e2_proj,
        circle1_err_des_fk=e1_des_fk,
        circle2_err_des_fk=e2_des_fk,
        workspace_npz=cfg.workspace_npz,
        z0_circle1=z1,
        z0_circle2=z2,
        k_nearest=cfg.k_nearest,
        alpha_u=cfg.alpha_u,
    )

    if cfg.export_csv:
        # Human-friendly CSV exports (VS Code-friendly).
        def _save_csv(path: Path, arr: np.ndarray) -> None:
            np.savetxt(path, np.asarray(arr, dtype=np.float64), delimiter=",", header="c1,c2,c3", comments="")

        tag = f"y40_r10_dp_0p1mm_n{cfg.points_per_circle}"
        c1_csv = out_dir / f"circle1_currents_{tag}.csv"
        c2_csv = out_dir / f"circle2_currents_{tag}.csv"
        _save_csv(c1_csv, U1)
        _save_csv(c2_csv, U2)
        combined = np.vstack([np.column_stack([np.ones(len(U1)), U1]), np.column_stack([2 * np.ones(len(U2)), U2])])
        comb_csv = out_dir / f"circle_currents_ypm40_r10_dp_0p1mm_n{cfg.points_per_circle}.csv"
        np.savetxt(comb_csv, combined, delimiter=",", header="circle_id,c1,c2,c3", comments="")
        print(f"Saved: {c1_csv}")
        print(f"Saved: {c2_csv}")
        print(f"Saved: {comb_csv}")

    plots_dir = Path("plots")
    plots_dir.mkdir(parents=True, exist_ok=True)
    plot_multiview(
        P_ok,
        np.vstack([p_des_1, p_des_2]),
        np.vstack([p_proj_1, p_proj_2]),
        np.vstack([P1_fk, P2_fk]),
        plots_dir / "fk_ik_test_dp_projection_multiview.png",
    )

    fig, ax = plt.subplots(1, 1, figsize=(12, 4))
    ax.plot(e1, label="circle1 ||proj-fk||")
    ax.plot(e2, label="circle2 ||proj-fk||")
    ax.axhline(cfg.threshold_traj_mm, color="k", lw=1.0, ls=":")
    ax.set_title("FK/IK error vs projected target")
    ax.set_xlabel("point index")
    ax.set_ylabel("error (mm)")
    ax.grid(True, alpha=0.25)
    ax.legend(loc="best")
    fig.tight_layout()
    fig.savefig(plots_dir / "fk_ik_test_dp_projection_error.png", dpi=200)
    plt.close(fig)

    print(f"Saved: {out_npz}")
    print("Saved: plots/fk_ik_test_dp_projection_multiview.png")
    print("Saved: plots/fk_ik_test_dp_projection_error.png")


if __name__ == "__main__":
    main()
